
// DISEÑO / USABILIDAD -> UX/UI -> BOOTCAMP UX/UI

// DB -> CREAR TU MODELO DE DATOS -> ARQUITECTOS DE DB - EXCLUSIVA

// SISTEMAS + INTEGRACIÓN CONTINUA -> DEVOPS  + SEGURIDAD -> BOOTCAMP DE CIBER

// DESRROLLO -> BACKEND -> LOGICA NEGOCIO + FLUJOS DE USARIO + HISTORIAS USUARIO

// -> PROJECT MANAGER + BACKEND -> MICROSER + LENGUAJES

// DESARROLLO -> FRONTEND -> -> LOGICA NEGOCIO + FLUJOS DE USARIO + HISTORIAS USUARIO

// PROJECT MANAGER + FRONT + MICROFRONTS + FRAME + LIBRERIAS....

// BOOTCAMP -> MENITRA = FSD ¿? -> 80% FRONT / 20% BACK

// OFERTAS FRONT - JS = 80%

// OFERTAS FRONT - APP NATIVAS = 20%

// OFERTAS BACK - JS = 10% - NODE [MENTIRA - SSR ISR SPG DEL FRONT]

// OFERTAS BACK - JAVA = 60%

// OFERTAS BACK - PYTHON = 30%

// OFERTAS BACK - PHP = DESVIRTUADO -> WORDPRESS != [PHP]

// OFERTAS BACK - PHP = SYMPHONY O LARAVEL + FRAMEWORKS -> CMR